# Generated by Django 2.2.12 on 2020-05-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(default=0, max_length=10, verbose_name='价格'),
        ),
    ]
