# Generated by Django 2.2.12 on 2020-05-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200528_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
