# Generated by Django 2.2.12 on 2020-05-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hits',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
