# Generated by Django 2.2.12 on 2020-05-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200529_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='admin', max_length=6)),
            ],
            options={
                'verbose_name_plural': '用户管理',
                'verbose_name': '用户管理',
            },
        ),
    ]
