# Generated by Django 2.2.12 on 2020-05-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0002_auto_20200528_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
        migrations.DeleteModel(
            name='hits',
        ),
    ]
